# Generated by Django 4.2.2 on 2023-07-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('shoping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartrecipes',
            name='recipe',
            field=models.ForeignKey(help_text='Выбор рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipe', unique=True, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='cartrecipes',
            name='shoping_cart',
            field=models.ForeignKey(help_text='Рецепты в корзине', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='shoping_cart.shopingcart', verbose_name='Корзина'),
        ),
    ]
