# Generated by Django 4.2.2 on 2023-07-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoping_cart', '0003_alter_cartrecipes_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartrecipes',
            constraint=models.UniqueConstraint(fields=('shoping_cart', 'recipe'), name='unique_shoping_cart_recipe'),
        ),
    ]
