# Generated by Django 4.2.2 on 2023-07-02 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientparam',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.CreateModel(
            name='AmountIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Количество ингредиентов', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Количество ингредиентов не должно быть отрицательным.')], verbose_name='Количество')),
                ('parametrs', models.ForeignKey(help_text='Имя и размерность ингредиента', on_delete=django.db.models.deletion.CASCADE, related_name='params', to='recipes.ingredientparam', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Кол-во ингредиентов',
                'verbose_name_plural': 'Кол-во ингредиентов',
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='recipes.amountingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингредиенты рецепта', to='recipes.amountingredient', verbose_name='Ингредиент'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
