# Generated by Django 4.2.2 on 2023-07-12 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата, когда был создан рецепт', verbose_name='Дата создания'),
        ),
    ]
