# Generated by Django 4.2.2 on 2023-06-28 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(help_text='Количество ингредиентов', validators=[django.core.validators.MinValueValidator(limit_value=0, message='Количество ингредиентов не должно быть отрицательным.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название тега', max_length=200, verbose_name='Название'),
        ),
    ]
