# Generated by Django 4.2.2 on 2023-07-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredientparam_options_amountingredient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientParam',
            new_name='Ingredient',
        ),
    ]
