# Generated by Django 3.2 on 2023-07-18 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230716_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Время готовки в минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Время готовки должно быть положительным.')], verbose_name='Время готовки'),
        ),
    ]
